/**
 * LayoScan — Demo Seed Script
 * Run: npm run seed  (from the server/ directory)
 *
 * Creates one demo restaurant, branch, 3 tables, an owner account,
 * 2 categories, and 4 products (2 with modifierGroups).
 * Logs the generated qrTokens so they can be used for manual testing.
 */

require('dotenv').config();
const mongoose = require('mongoose');

const Restaurant = require('../models/Restaurant');
const Branch     = require('../models/Branch');
const Table      = require('../models/Table');
const User       = require('../models/User');
const Category   = require('../models/Category');
const Product    = require('../models/Product');

async function seed() {
  const MONGO_URI = process.env.MONGO_URI;

  if (!MONGO_URI) {
    console.error('[Seed] ❌  MONGO_URI is not set.');
    console.error('       Copy server/.env.example → server/.env and fill in your connection string.');
    process.exit(1);
  }

  // ── Connect ──────────────────────────────────────────────────────────────────
  await mongoose.connect(MONGO_URI);
  console.log('[Seed] ✅  Connected to MongoDB\n');

  // ── Clear any previous demo data by name ─────────────────────────────────────
  const existingRestaurant = await Restaurant.findOne({ name: 'Demo Bistro' });
  if (existingRestaurant) {
    const rid = existingRestaurant._id;
    await Promise.all([
      Branch.deleteMany({ restaurantId: rid }),
      Table.deleteMany({ restaurantId: rid }),
      User.deleteMany({ restaurantId: rid }),
      Category.deleteMany({ restaurantId: rid }),
      Product.deleteMany({ restaurantId: rid }),
      Restaurant.deleteOne({ _id: rid }),
    ]);
    console.log('[Seed] 🗑   Cleared previous Demo Bistro data\n');
  }

  // ── Restaurant ───────────────────────────────────────────────────────────────
  const restaurant = await Restaurant.create({
    name:        'Demo Bistro',
    brandColor:  '#4F46E5',
    description: 'A cosy neighbourhood bistro — created by the LayoScan seed script.',
    contactInfo: {
      phone:   '+1-555-0100',
      email:   'hello@demobistro.test',
      address: '123 Main Street, Demo City, DC 00001',
    },
    socialLinks: {
      instagram: 'https://instagram.com/demobistro',
      website:   'https://demobistro.test',
    },
    subscriptionPlan: 'business',
  });
  console.log(`[Seed] 🍽   Restaurant → ${restaurant.name}  (id: ${restaurant._id})`);
  console.log(`            slug: ${restaurant.slug}\n`);

  // ── Branch ───────────────────────────────────────────────────────────────────
  const branch = await Branch.create({
    restaurantId: restaurant._id,
    name:         'Main Branch',
    address:      '123 Main Street, Demo City, DC 00001',
    currency:     'ETB',
    timezone:     'America/New_York',
  });
  console.log(`[Seed] 🏪   Branch → ${branch.name}  (id: ${branch._id})\n`);

  // ── Tables ───────────────────────────────────────────────────────────────────
  // qrToken is auto-generated by the Table pre-save hook
  const tables = await Table.create([
    { restaurantId: restaurant._id, branchId: branch._id, label: 'Table 1' },
    { restaurantId: restaurant._id, branchId: branch._id, label: 'Table 2' },
    { restaurantId: restaurant._id, branchId: branch._id, label: 'Table 3' },
  ]);
  console.log('[Seed] 🪑   Tables created:');
  tables.forEach((t) =>
    console.log(`            ${t.label.padEnd(10)} qrToken: ${t.qrToken}`)
  );
  console.log();

  // ── Owner User ───────────────────────────────────────────────────────────────
  // The User pre-save hook hashes passwordHash before storage
  const user = await User.create({
    restaurantId: restaurant._id,
    name:         'Demo Owner',
    email:        'demo@layoscan.test',
    passwordHash: 'Demo1234',
    role:         'owner',
  });
  console.log(`[Seed] 👤   Owner user → ${user.email}  (id: ${user._id})\n`);

  // ── Categories ───────────────────────────────────────────────────────────────
  const [starters, mains] = await Category.create([
    { restaurantId: restaurant._id, name: 'Starters', sortOrder: 1 },
    { restaurantId: restaurant._id, name: 'Mains',    sortOrder: 2 },
  ]);
  console.log('[Seed] 📂   Categories → Starters, Mains\n');

  // ── Products ─────────────────────────────────────────────────────────────────
  const products = await Product.create([
    // Starters (no modifiers)
    {
      restaurantId: restaurant._id,
      categoryId:   starters._id,
      name:         'Garlic Bread',
      description:  'Toasted sourdough with roasted garlic butter and fresh parsley.',
      price:        5.99,
    },
    {
      restaurantId: restaurant._id,
      categoryId:   starters._id,
      name:         'Tomato Soup',
      description:  'Creamy heirloom tomato bisque with a drizzle of basil oil.',
      price:        7.50,
    },

    // Mains (with modifiers)
    {
      restaurantId: restaurant._id,
      categoryId:   mains._id,
      name:         'Grilled Chicken Burger',
      description:  'Free-range chicken breast with lettuce, tomato, and house sauce on a brioche bun.',
      price:        13.99,
      modifierGroups: [
        {
          name:      'Spice Level',
          required:  false,
          minSelect: 0,
          maxSelect: 1,
          options: [
            { name: 'Mild',   priceDelta: 0 },
            { name: 'Medium', priceDelta: 0 },
            { name: 'Hot',    priceDelta: 0 },
          ],
        },
        {
          name:      'Add-ons',
          required:  false,
          minSelect: 0,
          maxSelect: 3,
          options: [
            { name: 'Extra Cheese', priceDelta: 1.50 },
            { name: 'Bacon',        priceDelta: 2.00 },
            { name: 'Avocado',      priceDelta: 1.75 },
          ],
        },
      ],
    },
    {
      restaurantId: restaurant._id,
      categoryId:   mains._id,
      name:         'Margherita Pizza',
      description:  'Neapolitan pizza with San Marzano tomatoes and fresh mozzarella.',
      price:        15.00,
      modifierGroups: [
        {
          name:      'Size',
          required:  true,
          minSelect: 1,
          maxSelect: 1,
          options: [
            { name: 'Small (9")',   priceDelta: 0    },
            { name: 'Medium (12")', priceDelta: 3.00 },
            { name: 'Large (15")',  priceDelta: 6.00 },
          ],
        },
      ],
    },
  ]);
  console.log(`[Seed] 🍔   Products → ${products.map((p) => p.name).join(', ')}\n`);

  // ── Summary ───────────────────────────────────────────────────────────────────
  console.log('═══════════════════════════════════════════════════════════');
  console.log('[Seed] ✅  Done! Use these values to test the API manually:\n');
  console.log(`  POST /api/auth/login`);
  console.log(`    { "email": "demo@layoscan.test", "password": "Demo1234" }\n`);
  console.log(`  GET /api/public/table/:qrToken`);
  tables.forEach((t) =>
    console.log(`    ${t.label.padEnd(10)} → ${t.qrToken}`)
  );
  console.log(`\n  GET /api/products/public?restaurantId=${restaurant._id}`);
  console.log('═══════════════════════════════════════════════════════════\n');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('[Seed] ❌  Fatal error:', err.message);
  process.exit(1);
});
