const crypto = require('crypto');
const Table = require('../models/Table');

// ── GET /api/tables?branchId= ─────────────────────────────────────────────────
const listTables = async (req, res, next) => {
  try {
    const filter = { restaurantId: req.tenantId };
    if (req.query.branchId) filter.branchId = req.query.branchId;

    const tables = await Table.find(filter).sort({ label: 1 });
    return res.json({ success: true, tables });
  } catch (err) {
    return next(err);
  }
};

// ── POST /api/tables ──────────────────────────────────────────────────────────
const createTable = async (req, res, next) => {
  try {
    const { branchId, label } = req.body;

    if (!branchId || !label) {
      return res.status(400).json({
        success: false,
        message: 'branchId and label are required.',
      });
    }

    // qrToken is auto-generated by the Table pre-save hook
    const table = await Table.create({
      restaurantId: req.tenantId,
      branchId,
      label,
    });

    return res.status(201).json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

// ── PATCH /api/tables/:id ─────────────────────────────────────────────────────
const updateTable = async (req, res, next) => {
  try {
    // Only allow label and isActive to be changed via this endpoint
    const ALLOWED = ['label', 'isActive'];
    const updates = {};
    for (const field of ALLOWED) {
      if (req.body[field] !== undefined) updates[field] = req.body[field];
    }

    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      updates,
      { new: true, runValidators: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    return res.json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

// ── DELETE /api/tables/:id (soft-delete) ──────────────────────────────────────
const deleteTable = async (req, res, next) => {
  try {
    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      { isActive: false },
      { new: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    return res.json({ success: true, message: 'Table deactivated successfully.', table });
  } catch (err) {
    return next(err);
  }
};

// ── POST /api/tables/:id/regenerate-qr ───────────────────────────────────────
const regenerateQR = async (req, res, next) => {
  try {
    const newToken = crypto.randomBytes(8).toString('hex');

    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      { qrToken: newToken },
      { new: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    return res.json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

module.exports = { listTables, createTable, updateTable, deleteTable, regenerateQR };
