const crypto = require('crypto');
const Table = require('../models/Table');
const Branch = require('../models/Branch');

const emitTableUpdated = (req, table) => {
  const io = req.app.get('io');
  if (io && table) io.to(`restaurant:${table.restaurantId}`).emit('table:updated', table);
};

// ── GET /api/tables?branchId= ─────────────────────────────────────────────────
const listTables = async (req, res, next) => {
  try {
    const filter = { restaurantId: req.tenantId };
    if (req.query.branchId) filter.branchId = req.query.branchId;

    const tables = await Table.find(filter).sort({ label: 1 });
    return res.json({ success: true, tables });
  } catch (err) {
    return next(err);
  }
};

// ── POST /api/tables ──────────────────────────────────────────────────────────
const createTable = async (req, res, next) => {
  try {
    const { branchId, label } = req.body;

    if (!branchId || !label) {
      return res.status(400).json({
        success: false,
        message: 'branchId and label are required.',
      });
    }

    // Verify branch belongs to tenant
    const branch = await Branch.findOne({ _id: branchId, restaurantId: req.tenantId });
    if (!branch) {
      return res.status(400).json({
        success: false,
        message: 'Branch is invalid or does not belong to your restaurant.',
      });
    }

    // qrToken is auto-generated by the Table pre-save hook
    const table = await Table.create({
      restaurantId: req.tenantId,
      branchId,
      label: label.trim(),
    });

    return res.status(201).json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

// ── POST /api/tables/bulk ─────────────────────────────────────────────────────
const createBulkTables = async (req, res, next) => {
  try {
    const { branchId, tables } = req.body;

    if (!branchId || !Array.isArray(tables) || tables.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'branchId and a non-empty tables array are required.',
      });
    }

    // Verify branch belongs to tenant
    const branch = await Branch.findOne({ _id: branchId, restaurantId: req.tenantId });
    if (!branch) {
      return res.status(400).json({
        success: false,
        message: 'Branch is invalid or does not belong to your restaurant.',
      });
    }

    // Prepare table documents with explicit qrTokens generated before insert
    const docs = tables.map((t) => {
      const labelStr = (t.label || '').trim();
      if (!labelStr) {
        throw new Error('All tables in bulk insert must have a valid label.');
      }
      return {
        restaurantId: req.tenantId,
        branchId,
        label: labelStr,
        qrToken: crypto.randomBytes(8).toString('hex'),
        isActive: true,
      };
    });

    const createdTables = await Table.insertMany(docs);
    return res.status(201).json({ success: true, tables: createdTables });
  } catch (err) {
    if (err.message && err.message.includes('must have a valid label')) {
      return res.status(400).json({ success: false, message: err.message });
    }
    return next(err);
  }
};

// ── PATCH /api/tables/bulk/regenerate-qr ──────────────────────────────────────
const bulkRegenerateQR = async (req, res, next) => {
  try {
    const { ids } = req.body;

    if (!Array.isArray(ids) || ids.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'An array of table ids is required.',
      });
    }

    // Verify tenant ownership for every id requested
    const count = await Table.countDocuments({
      _id: { $in: ids },
      restaurantId: req.tenantId,
    });

    if (count !== ids.length) {
      return res.status(403).json({
        success: false,
        message: 'One or more tables do not belong to your restaurant or were not found.',
      });
    }

    // Generate fresh qrToken for each table document
    const updatePromises = ids.map((id) =>
      Table.findOneAndUpdate(
        { _id: id, restaurantId: req.tenantId },
        { qrToken: crypto.randomBytes(8).toString('hex') },
        { new: true }
      )
    );

    const updatedTables = await Promise.all(updatePromises);
    return res.json({ success: true, tables: updatedTables });
  } catch (err) {
    return next(err);
  }
};

// ── PATCH /api/tables/bulk/deactivate ─────────────────────────────────────────
const bulkDeactivate = async (req, res, next) => {
  try {
    const { ids } = req.body;

    if (!Array.isArray(ids) || ids.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'An array of table ids is required.',
      });
    }

    // Verify tenant ownership for every id requested
    const count = await Table.countDocuments({
      _id: { $in: ids },
      restaurantId: req.tenantId,
    });

    if (count !== ids.length) {
      return res.status(403).json({
        success: false,
        message: 'One or more tables do not belong to your restaurant or were not found.',
      });
    }

    await Table.updateMany(
      { _id: { $in: ids }, restaurantId: req.tenantId },
      { isActive: false }
    );

    const updatedTables = await Table.find({
      _id: { $in: ids },
      restaurantId: req.tenantId,
    });

    return res.json({ success: true, tables: updatedTables });
  } catch (err) {
    return next(err);
  }
};

// ── PATCH /api/tables/:id/release ───────────────────────────────────────────────
const releaseTable = async (req, res, next) => {
  try {
    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      {
        status: 'available',
        occupiedSince: null,
        activeSessionToken: null,
        sessionExpiresAt: null,
        sessionLocationVerified: null,
      },
      { new: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    emitTableUpdated(req, table);
    return res.json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

// ── PATCH /api/tables/bulk/release ──────────────────────────────────────────────
const bulkRelease = async (req, res, next) => {
  try {
    const { ids } = req.body;
    const uniqueIds = Array.isArray(ids) ? [...new Set(ids)] : [];

    if (uniqueIds.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'An array of table ids is required.',
      });
    }

    const count = await Table.countDocuments({
      _id: { $in: uniqueIds },
      restaurantId: req.tenantId,
    });

    if (count !== uniqueIds.length) {
      return res.status(403).json({
        success: false,
        message: 'One or more tables do not belong to your restaurant or were not found.',
      });
    }

    await Table.updateMany(
      { _id: { $in: uniqueIds }, restaurantId: req.tenantId },
      {
        status: 'available',
        occupiedSince: null,
        activeSessionToken: null,
        sessionExpiresAt: null,
        sessionLocationVerified: null,
      }
    );

    const updatedTables = await Table.find({
      _id: { $in: uniqueIds },
      restaurantId: req.tenantId,
    });
    updatedTables.forEach((table) => emitTableUpdated(req, table));

    return res.json({ success: true, tables: updatedTables });
  } catch (err) {
    return next(err);
  }
};

// ── PATCH /api/tables/:id ─────────────────────────────────────────────────────
const updateTable = async (req, res, next) => {
  try {
    // Only allow label and isActive to be changed via this endpoint
    const ALLOWED = ['label', 'isActive'];
    const updates = {};
    for (const field of ALLOWED) {
      if (req.body[field] !== undefined) updates[field] = req.body[field];
    }

    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      updates,
      { new: true, runValidators: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    return res.json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

// ── DELETE /api/tables/:id (soft-delete) ──────────────────────────────────────
const deleteTable = async (req, res, next) => {
  try {
    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      { isActive: false },
      { new: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    return res.json({ success: true, message: 'Table deactivated successfully.', table });
  } catch (err) {
    return next(err);
  }
};

// ── POST /api/tables/:id/regenerate-qr ───────────────────────────────────────
const regenerateQR = async (req, res, next) => {
  try {
    const newToken = crypto.randomBytes(8).toString('hex');

    const table = await Table.findOneAndUpdate(
      { _id: req.params.id, restaurantId: req.tenantId },
      { qrToken: newToken },
      { new: true }
    );

    if (!table) {
      return res.status(404).json({ success: false, message: 'Table not found.' });
    }

    return res.json({ success: true, table });
  } catch (err) {
    return next(err);
  }
};

module.exports = {
  listTables,
  createTable,
  createBulkTables,
  bulkRegenerateQR,
  bulkDeactivate,
  releaseTable,
  bulkRelease,
  updateTable,
  deleteTable,
  regenerateQR,
};
